---
- name: Setup timesketch on instance
  hosts: localhost
  become: yes
  tasks:
    - name: Install docker
      apt:
        name: ['apt-transport-https','ca-certificates', 'curl', 'software-properties-common']
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker

    - name: Get ubuntu version
      command: lsb_release -cs
      register: ubuntu_version
      tags:
        - docker

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable
        state: present
      tags:
        - docker

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes
    
    - name: Install docker compose plugin
      apt:
        name: docker-compose-plugin
        state: present
        update_cache: yes

    - name: Download timesketch deployment script
      get_url:
        url: https://raw.githubusercontent.com/google/timesketch/refs/tags/20250408/contrib/deploy_timesketch.sh
        dest: /opt/timesketch_deploy.sh
        mode: '0755'
      tags:
        - timesketch
    
    - name: Check if /opt/timesketch directory exists
      command: test -d /opt/timesketch
      register: timesketch_dir_exists
      ignore_errors: true

    - name: Save the result for future use
      set_fact:
        timesketch_exists: "{{ timesketch_dir_exists.rc == 0 }}"

    - name: Run the deployment script
      command: /opt/timesketch_deploy.sh --skip-create-user --start-container
      args:
        chdir: /opt
      when: not timesketch_exists
      tags:
        - timesketch

    - name: Check response from timesketch
      uri:
        url: "http://localhost"
      register: result
      retries: 3
      delay: 10
      until: result.status == 200
